import {
  Banknote,
  Bike,
  Book,
  Briefcase,
  Building2,
  Car,
  CreditCard,
  Dumbbell,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  PawPrint,
  PiggyBank,
  PlaneTakeoff,
  Plug,
  PlusCircle,
  Repeat,
  ShoppingBag,
  ShoppingCart,
  Shirt,
  Smartphone,
  Sparkles,
  Tag,
  TrendingUp,
  Users,
  Utensils,
  Wallet,
  Wifi,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  wallet: Wallet,
  banknote: Banknote,
  "credit-card": CreditCard,
  landmark: Landmark,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  home: Home,
  utensils: Utensils,
  car: Car,
  bike: Bike,
  "heart-pulse": HeartPulse,
  book: Book,
  "graduation-cap": GraduationCap,
  sparkles: Sparkles,
  repeat: Repeat,
  tag: Tag,
  "plus-circle": PlusCircle,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  gift: Gift,
  "plane-takeoff": PlaneTakeoff,
  wifi: Wifi,
  plug: Plug,
  smartphone: Smartphone,
  dumbbell: Dumbbell,
  users: Users,
  briefcase: Briefcase,
  "paw-print": PawPrint,
  building: Building2,
};

export const ICON_CHOICES = Object.keys(ICONS);

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Tag;
}
